version: "3.9"

services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      # - ${DATA_DIR}/maps:/meteo
      - ${DATA_DIR}/opendata:/opendata
      - ${PROJECT_DIR}/scripts:/scripts

    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}
      GRACE_PERIOD: ${GRACE_PERIOD}
      ON_DATA_READY_DATASETS: ${ON_DATA_READY_DATASETS}
      MAPS_URL: ${MAPS_URL}
      AGGREGATIONS_TRANGES: ${AGGREGATIONS_TRANGES}
      AGGREGATIONS_DSN: ${AGGREGATIONS_DSN}
      AGGREGATIONS_LASTDAYS: ${AGGREGATIONS_LASTDAYS}
      S3_ENABLE: ${S3_ENABLE}
      S3_ENABLE_CONNECTOR: ${S3_ENABLE_CONNECTOR}
      S3_HOST: ${S3_HOST}
      S3_PORT: ${S3_PORT}
      S3_KEY_ID: ${S3_KEY_ID}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_VERIFY_SSL: ${S3_VERIFY_SSL}

  app:
    image: harbor-ada.hpc.cineca.it/meteo-hub-production/meteo-hub-ui:latest
    environment:
      ACTIVATE: ${ACTIVATE_APP_FRONTEND}
    # volumes:
    #   - ${DATA_DIR}/maps:/meteo

  flower:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config

  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      - ${DATA_DIR}/opendata:/opendata
    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}
      GRACE_PERIOD: ${GRACE_PERIOD}

  celerybeat:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

  nifi:
    build:
      context: ${PROJECT_DIR}/builds/ingestor
      args:
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    image: meteohub/nifi:${RAPYDO_VERSION}
    restart: always
    volumes:
      - ${PROJECT_DIR}/nifi/scripts:/home/nifi/ingest
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      # - ${DATA_DIR}/nifi:/opt/nifi
      - ${DATA_DIR}/nifi/conf:/opt/nifi/nifi-current/conf
      - ${DATA_DIR}/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ${DATA_DIR}/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ${DATA_DIR}/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ${DATA_DIR}/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ${DATA_DIR}/nifi/state:/opt/nifi/nifi-current/state
      - ${DATA_DIR}/nifi/logs:/opt/nifi/nifi-current/logs
      - ${DATA_DIR}/nifi/error_flowfiles:/opt/nifi/nifi_error_flowfile
      - ${DATA_DIR}/nifi/amqp_flowfiles:/opt/nifi/nifi_ok_flowfile
      - ${DATA_DIR}/nifi/nfs:/opt/nifi/nfs
      - ${DATA_DIR}/seasonal:/opt/nifi/seasonal_grib

    environment:
      ACTIVATE: ${ACTIVATE_NIFI}
      APP_MODE: ${APP_MODE}
      CURRENT_UID: ${CURRENT_UID}
      CURRENT_GID: ${CURRENT_GID}

      NIFI_SENSITIVE_PROPS_KEY: ${NIFI_SENSITIVE_PROPS_KEY}

      ALCHEMY_HOST: ${ALCHEMY_HOST}
      ALCHEMY_PORT: ${ALCHEMY_PORT}
      ALCHEMY_USER: "${ALCHEMY_USER}"
      ALCHEMY_PASSWORD: "${ALCHEMY_PASSWORD}"

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

      NIFI_EMAIL_FOR_ALERT: "${NIFI_EMAIL_FOR_ALERT}"
      NIFI_EMAIL_HEADER: "${NIFI_EMAIL_HEADER}"
      FTP_USER: "${FTP_USER}"
      FTP_PASSWORD_DPC: "${FTP_PASSWORD_DPC}"
      RADAR_FTP_USER: "${RADAR_FTP_USER}"
      RADAR_FTP_PASSWORD: "${RADAR_FTP_PASSWORD}"
      NIFI_DATABASE_URL: "${NIFI_DATABASE_URL}"
      MAX_DAYS_NIFI_DATA: ${MAX_DAYS_NIFI_DATA}
      MAX_DAYS_NIFI_LOGS: $MAX_DAYS_NIFI_LOGS
      NIFI_ARKIMET_CONFIG_PATH: ${NIFI_ARKIMET_CONFIG_PATH}
      NIFI_POSTGRES_DRIVER_PATH: "${NIFI_POSTGRES_DRIVER_PATH}"
      NIFI_TEMP_DIR: ${NIFI_TEMP_DIR}
      ARPAE_QUEUE: "${ARPAE_QUEUE}"
      METEOSENSOR_QUEUE: "${METEOSENSOR_QUEUE}"
      AGGREGATIONS_TRANGES: ${AGGREGATIONS_TRANGES}
      AGGREGATIONS_DSN: ${AGGREGATIONS_DSN}
      SSL_TRUSTORE_FILENAME: "${SSL_TRUSTORE_FILENAME}"
      AIM_S3_SECRET_KEY: "${AIM_S3_SECRET_KEY}"
      AIM_S3_ACCESS_KEY: "${AIM_S3_ACCESS_KEY}"
      AIM_S3_ENDPOINT: "${AIM_S3_ENDPOINT}"

    networks:
      default:

  strapi:
    image: harbor-ada.hpc.cineca.it/meteo-hub-production/meteo-hub-strapi:latest
    restart: unless-stopped
    # env_file: ${PROJECT_DIR}/builds/strapi/.env
    environment:
      ACTIVATE: ${ACTIVATE_STRAPI}
      DATABASE_CLIENT: ${CMS_DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${CMS_DATABASE_PORT}
      DATABASE_NAME: ${CMS_DATABASE_NAME}
      DATABASE_USERNAME: ${CMS_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${CMS_DATABASE_PASSWORD}
      JWT_SECRET: ${CMS_JWT_SECRET}
      ADMIN_JWT_SECRET: ${CMS_ADMIN_JWT_SECRET}
      APP_KEYS: ${CMS_APP_KEYS}
      NODE_ENV: production
      HOST: ${CMS_HOST}
      PORT: ${CMS_PORT}
      API_TOKEN_SALT: ${CMS_API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${CMS_TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${CMS_ENCRYPTION_KEY}
      DATABASE_SSL: ${CMS_DATABASE_SSL}
      DATABASE_FILENAME: ${CMS_DATABASE_FILENAME}
      DATA_PATH: ${DATA_DIR}
      DB_PATH_RELATIVE: ${CMS_DB_PATH_RELATIVE}
      UPLOAD_PATH_RELATIVE: ${CMS_UPLOAD_PATH_RELATIVE}
      # STRAPI_SERVER_RELATIVE_PATH: /

    volumes:
      - ${DATA_DIR}/strapi/${CMS_UPLOAD_PATH_RELATIVE}:/opt/app/public/uploads
    # ports:
    #   - "1337:1337"
    networks:
      default:
    depends_on:
      - strapiDB
    healthcheck:
      test: ["CMD-SHELL", "ping -c 1 localhost:1337 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    # env_file: ${PROJECT_DIR}/builds/strapi/.env
    image: postgres:16.0-alpine
    environment:
      ACTIVATE: ${ACTIVATE_STRAPI}
      POSTGRES_USER: ${CMS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${CMS_DATABASE_PASSWORD}
      POSTGRES_DB: ${CMS_DATABASE_NAME}
      HOST: ${CMS_DATABASE_HOST}
      PORT: ${CMS_DATABASE_PORT}
      APP_KEYS: ${CMS_APP_KEYS}
      API_TOKEN_SALT: ${CMS_API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${CMS_ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${CMS_TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${CMS_ENCRYPTION_KEY}
      DATABASE_CLIENT: ${CMS_DATABASE_CLIENT}
      DATABASE_HOST: ${CMS_DATABASE_HOST}
      DATABASE_PORT: ${CMS_DATABASE_PORT}
      DATABASE_NAME: ${CMS_DATABASE_NAME}
      DATABASE_USERNAME: ${CMS_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${CMS_DATABASE_PASSWORD}
      DATABASE_SSL: ${CMS_DATABASE_SSL}
      DATABASE_FILENAME: ${CMS_DATABASE_FILENAME}
      JWT_SECRET: ${CMS_JWT_SECRET}
    volumes:
      - ${DATA_DIR}/strapi/${CMS_DB_PATH_RELATIVE}:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    expose:
      - 5432
    networks:
      default:
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ui:
    image: harbor-ada.hpc.cineca.it/meteo-hub-production/meteo-cms-ui:latest
    restart: unless-stopped
    # env_file: ${PROJECT_DIR}/builds/strapi/.env
    environment:
      ACTIVATE: ${ACTIVATE_UI}
      PORT: 4200
# volumes:
#   strapiDB-data:
#     driver: local
#     driver_opts:
#       type: none
#       # device: ${STRAPI_DATA_PATH}/${DB_PATH_RELATIVE}
#       device: ${DATA_DIR}/strapi/${DB_PATH_RELATIVE}
#       o: bind
#   strapi-data:
#     driver: local
#     driver_opts:
#       type: none
#       # device: ${STRAPI_DATA_PATH}/${UPLOAD_PATH_RELATIVE}
#       device: ${DATA_DIR}/strapi/${UPLOAD_PATH_RELATIVE}
#       o: bind

