version: "3.9"

services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      # - ${DATA_DIR}/maps:/meteo
      - ${DATA_DIR}/opendata:/opendata
      - ${PROJECT_DIR}/scripts:/scripts

    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}
      GRACE_PERIOD: ${GRACE_PERIOD}
      ON_DATA_READY_DATASETS: ${ON_DATA_READY_DATASETS}
      MAPS_URL: ${MAPS_URL}
      AGGREGATIONS_TRANGES: ${AGGREGATIONS_TRANGES}
      AGGREGATIONS_DSN: ${AGGREGATIONS_DSN}
      AGGREGATIONS_LASTDAYS: ${AGGREGATIONS_LASTDAYS}

  frontend:
    environment:
      INJECT_FRONTEND_DEBUG: ${FRONTEND_DEBUG}
      INJECT_LASTDAYS: ${LASTDAYS}
      INJECT_PLATFORM: ${PLATFORM}
      INJECT_MAPS_URL: ${MAPS_URL}
      INJECT_TILES_URL: ${TILES_URL}
      INJECT_PROJECT_HOME: ${PROJECT_HOME}
      INJECT_COOKIE_POLICY_URL: ${COOKIE_POLICY_URL}
      INJECT_GRACE_PERIOD: ${GRACE_PERIOD}
      INJECT_ON_DATA_READY_DATASETS: ${ON_DATA_READY_DATASETS}
      INJECT_WARNING_MSG: ${WARNING_MSG}
    # volumes:
    #   - ${DATA_DIR}/maps:/meteo

  flower:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config

  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      - ${DATA_DIR}/opendata:/opendata
    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}
      GRACE_PERIOD: ${GRACE_PERIOD}

  celerybeat:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

  nifi:
    build:
      context: ${PROJECT_DIR}/builds/ingestor
      args:
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    #legacy image until issue #410 is not solved
    image: meteohub/nifi-legacy:${RAPYDO_VERSION}
    #image: meteohub/nifi:${RAPYDO_VERSION}
    restart: always
    volumes:
      - ${PROJECT_DIR}/nifi/scripts:/home/nifi/ingest
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      # - ${DATA_DIR}/nifi:/opt/nifi
      - ${DATA_DIR}/nifi/conf:/opt/nifi/nifi-current/conf
      - ${DATA_DIR}/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ${DATA_DIR}/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ${DATA_DIR}/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ${DATA_DIR}/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ${DATA_DIR}/nifi/state:/opt/nifi/nifi-current/state
      - ${DATA_DIR}/nifi/logs:/opt/nifi/nifi-current/logs
      - ${DATA_DIR}/nifi/error_flowfiles:/opt/nifi/nifi_error_flowfile
      - ${DATA_DIR}/nifi/amqp_flowfiles:/opt/nifi/nifi_ok_flowfile

    environment:
      ACTIVATE: ${ACTIVATE_NIFI}
      APP_MODE: ${APP_MODE}
      CURRENT_UID: ${CURRENT_UID}
      CURRENT_GID: ${CURRENT_GID}

      NIFI_SENSITIVE_PROPS_KEY: ${NIFI_SENSITIVE_PROPS_KEY}

      ALCHEMY_HOST: ${ALCHEMY_HOST}
      ALCHEMY_PORT: ${ALCHEMY_PORT}
      ALCHEMY_USER: "${ALCHEMY_USER}"
      ALCHEMY_PASSWORD: "${ALCHEMY_PASSWORD}"

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

      NIFI_EMAIL_FOR_ALERT: "${NIFI_EMAIL_FOR_ALERT}"
      NIFI_EMAIL_HEADER: "${NIFI_EMAIL_HEADER}"
      FTP_USER: "${FTP_USER}"
      FTP_PASSWORD_DPC: "${FTP_PASSWORD_DPC}"
      NIFI_DATABASE_URL: "${NIFI_DATABASE_URL}"
      MAX_DAYS_NIFI_DATA: ${MAX_DAYS_NIFI_DATA}
      MAX_DAYS_NIFI_LOGS: $MAX_DAYS_NIFI_LOGS
      NIFI_ARKIMET_CONFIG_PATH: ${NIFI_ARKIMET_CONFIG_PATH}
      NIFI_POSTGRES_DRIVER_PATH: "${NIFI_POSTGRES_DRIVER_PATH}"
      NIFI_TEMP_DIR: ${NIFI_TEMP_DIR}
      ARPAE_QUEUE: "${ARPAE_QUEUE}"
      MULTIMODEL_QUEUE: "${MULTIMODEL_QUEUE}"
      AGGREGATIONS_TRANGES: ${AGGREGATIONS_TRANGES}
      AGGREGATIONS_DSN: ${AGGREGATIONS_DSN}

    networks:
      default:
      
  strapi:
    image: harbor-ada.hpc.cineca.it/meteo-hub-production/meteo-hub-strapi:latest
    restart: unless-stopped
    # env_file: ${PROJECT_DIR}/builds/strapi/.env
    environment:
      ACTIVATE: ${ACTIVATE_STRAPI}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DATABASE_SSL: ${DATABASE_SSL}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      DATA_PATH: ${DATA_PATH}
      DB_PATH_RELATIVE: ${DB_PATH_RELATIVE}
      UPLOAD_PATH_RELATIVE: ${UPLOAD_PATH_RELATIVE}
      API_RELATIVE_PATH: ${API_RELATIVE_PATH}

    volumes:
      - ${DATA_PATH}/${UPLOAD_PATH_RELATIVE}:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      default:
    depends_on:
      - strapiDB
    healthcheck:
      test: ["CMD-SHELL", "ping -c 1 localhost:1337 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    # env_file: ${PROJECT_DIR}/builds/strapi/.env
    image: postgres:16.0-alpine
    environment:
      ACTIVATE: ${ACTIVATE_STRAPIDB}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ${DATA_PATH}/${DB_PATH_RELATIVE}:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    expose:
      - 5432
    networks:
      default:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# volumes:
#   strapiDB-data: 
#     driver: local
#     driver_opts:
#       type: none
#       device: ${DATA_PATH}/${DB_PATH_RELATIVE}
#       o: bind
#   strapi-data:
#     driver: local
#     driver_opts:
#       type: none
#       device: ${DATA_PATH}/${UPLOAD_PATH_RELATIVE}
#       o: bind
  
