version: "3.8"

services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      - ${DATA_DIR}/maps:/meteo
      - ${DATA_DIR}/opendata:/opendata
      - ${PROJECT_DIR}/scripts:/scripts

    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}

  frontend:
    environment:
      INJECT_FRONTEND_DEBUG: ${FRONTEND_DEBUG}
      INJECT_LASTDAYS: ${LASTDAYS}
      INJECT_PLATFORM: ${PLATFORM}
      INJECT_MAPS_URL: ${MAPS_URL}
      INJECT_TILES_URL: ${TILES_URL}
    volumes:
      - ${DATA_DIR}/maps:/meteo

  postgres:
    ports:
      - ${ALCHEMY_PORT}:${ALCHEMY_PORT}

  rabbit:
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}

  flower:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config

  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      - ${DATA_DIR}/opendata:/opendata
    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}

  celery-beat:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

  nifi:
    build: ${PROJECT_DIR}/builds/ingestor
    image: meteohub/nifi:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/nifi:/opt/nifi
      - ${DATA_DIR}/nifi/scripts:/home/nifi/ingest
    ports:
      - 8070:8080
    environment:
      ACTIVATE: ${ACTIVATE_NIFI}
    networks:
      default:

  # arkimet:
  #   restart: always
  #   build:
  #     context: ${PROJECT_DIR}/builds/arkimet
  #     # args:
  #     #   RAPYDO_VERSION: ${RAPYDO_VERSION}
  #     #   CURRENT_UID: ${CURRENT_UID}
  #   image: rapydo/arkimet:${RAPYDO_VERSION}
  #   # expose:
  #   #   - 8090
  #   ports:
  #     - 8090:8090
  #   networks:
  #     default:
  #       aliases:
  #         - arkimet
  #   volumes:
  #     - ${DATA_DIR}/arkimet:/datasets
  #   environment:
  #     ACTIVATE: 1
# volumes:
#   -

# networks:
#   -

