version: "3.9"

services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      # - ${DATA_DIR}/maps:/meteo
      - ${DATA_DIR}/opendata:/opendata
      - ${PROJECT_DIR}/scripts:/scripts

    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}

  frontend:
    environment:
      INJECT_FRONTEND_DEBUG: ${FRONTEND_DEBUG}
      INJECT_LASTDAYS: ${LASTDAYS}
      INJECT_PLATFORM: ${PLATFORM}
      INJECT_MAPS_URL: ${MAPS_URL}
      INJECT_TILES_URL: ${TILES_URL}
    # volumes:
    #   - ${DATA_DIR}/maps:/meteo

  flower:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config

  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      - ${DATA_DIR}/opendata:/opendata
    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}

  celery-beat:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

  nifi:
    build:
      context: ${PROJECT_DIR}/builds/ingestor
      args:
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    image: meteohub/nifi:${RAPYDO_VERSION}
    restart: always
    volumes:
      - ${PROJECT_DIR}/nifi/scripts:/home/nifi/ingest
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      # - ${DATA_DIR}/nifi:/opt/nifi
      - ${DATA_DIR}/nifi/conf:/opt/nifi/nifi-current/conf
      - ${DATA_DIR}/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ${DATA_DIR}/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ${DATA_DIR}/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ${DATA_DIR}/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ${DATA_DIR}/nifi/state:/opt/nifi/nifi-current/state
      - ${DATA_DIR}/nifi/logs:/opt/nifi/nifi-current/logs

    environment:
      ACTIVATE: ${ACTIVATE_NIFI}
      CURRENT_UID: ${CURRENT_UID}
      CURRENT_GID: ${CURRENT_GID}
    networks:
      default:
# volumes:
#   -

# networks:
#   -

