version: "3.8"

services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      # - ${DATA_DIR}/maps:/meteo
      - ${DATA_DIR}/opendata:/opendata
      - ${PROJECT_DIR}/scripts:/scripts

    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}

  frontend:
    environment:
      INJECT_FRONTEND_DEBUG: ${FRONTEND_DEBUG}
      INJECT_LASTDAYS: ${LASTDAYS}
      INJECT_PLATFORM: ${PLATFORM}
      INJECT_MAPS_URL: ${MAPS_URL}
      INJECT_TILES_URL: ${TILES_URL}
    # volumes:
    #   - ${DATA_DIR}/maps:/meteo

  flower:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config

  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/user_repo:/data
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      - ${DATA_DIR}/arkimet_conf:/arkimet/config
      - ${DATA_DIR}/opendata:/opendata
    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}

  celery-beat:
    build: ${PROJECT_DIR}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

  nifi:
    build: ${PROJECT_DIR}/builds/ingestor
    image: meteohub/nifi:${RAPYDO_VERSION}
    restart: always
    volumes:
      - ${DATA_DIR}/arkimet:/arkimet/datasets
      # - ${DATA_DIR}/nifi:/opt/nifi
    ports:
      - 8070:8080
    environment:
      ACTIVATE: ${ACTIVATE_NIFI}
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      NIFI_WEB_HTTP_PORT: 8080
    networks:
      default:
# volumes:
#   -

# networks:
#   -

