# Customize this file to include compose configurations common to bluprints
version: "3"

services:
  backend:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: meteohub/backend:${RAPYDO_VERSION}

    volumes:
      - ${VANILLA_DIR}/data/user_repo:/data
      - ${VANILLA_DIR}/data/arkimet:/arkimet/datasets
      - ${VANILLA_DIR}/data/arkimet_conf:/arkimet/config
      - ${VANILLA_DIR}/data/maps:/meteo
      - ${VANILLA_DIR}/data/opendata:/opendata
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/scripts:/scripts

    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}

  frontend:
    environment:
      INJECT_FRONTEND_DEBUG: ${FRONTEND_DEBUG}
      INJECT_LASTDAYS: ${LASTDAYS}
      INJECT_PLATFORM: ${PLATFORM}
      INJECT_MAPS_URL: ${MAPS_URL}
      INJECT_TILES_URL: ${TILES_URL}
    volumes:
      - ${VANILLA_DIR}/data/maps:/meteo

  postgres:
    # image: postgres:11.5-alpine
    ports:
      - ${ALCHEMY_PORT}:${ALCHEMY_PORT}

  rabbit:
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}

  #  nifi:
  #    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/nifi
  #    image: meteohub/nifi:${RAPYDO_VERSION}
  #    ports:
  #      - 8070:8080
  #    environment:
  #      ACTIVATE: ${ACTIVATE_NIFI}

  flower:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    # build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/tmpbackend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/user_repo:/data
      - ${VANILLA_DIR}/data/arkimet:/arkimet/datasets
      - ${VANILLA_DIR}/data/arkimet_conf:/arkimet/config

  celery:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    # build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/tmpbackend
    image: meteohub/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/user_repo:/data
      - ${VANILLA_DIR}/data/arkimet:/arkimet/datasets
      - ${VANILLA_DIR}/data/arkimet_conf:/arkimet/config
      - ${VANILLA_DIR}/data/opendata:/opendata
    environment:
      LASTDAYS: ${LASTDAYS}
      PLATFORM: ${PLATFORM}

  celery-beat:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    # build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/tmpbackend
    image: meteohub/backend:${RAPYDO_VERSION}

  # arkimet:
  #   restart: always
  #   build:
  #     context: ${PROJECT_DIR}/builds/arkimet
  #     # args:
  #     #   RAPYDO_VERSION: ${RAPYDO_VERSION}
  #     #   CURRENT_UID: ${CURRENT_UID}
  #   image: rapydo/arkimet:${RAPYDO_VERSION}
  #   # expose:
  #   #   - 8090
  #   ports:
  #     - 8090:8090
  #   networks:
  #     app_net:
  #       aliases:
  #         - arkimet
  #   volumes:
  #     - ${VANILLA_DIR}/data/arkimet:/datasets
  #   environment:
  #     ACTIVATE: 1
# volumes:
#   -

# networks:
#   -

