version: "3.9"

services:
  nifi:
    ports:
      - 8070:8080
    environment:
      ACTIVATE: ${ACTIVATE_NIFI}
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      NIFI_WEB_HTTP_PORT: 8080
  minio:
    command: server --console-address ":9001" /data --address ":${S3_PORT}"
  strapi:
    image: harbor-ada.hpc.cineca.it/meteo-hub-staging/meteo-hub-strapi:latest
    ports:
      - "1337:1337"
    environment:
      START_MODE: develop
  ui:
    image: harbor-ada.hpc.cineca.it/meteo-hub-staging/meteo-cms-ui:latest
    ports:
      - "4200:4200"
  app:
    image: harbor-ada.hpc.cineca.it/meteo-hub-production/meteo-hub-ui:latest-pre
    ports:
      - "80:80"
