version: "3.8"

services:
  postgres:
    ports:
      - ${ALCHEMY_PORT}:${ALCHEMY_PORT}

  rabbit:
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}

  nifi:
    ports:
      - 8070:8443
    volumes:
      - ssl_certs:/ssl
    environment:
      ACTIVATE: ${ACTIVATE_NIFI}

      NIFI_SENSITIVE_PROPS_KEY: ${NIFI_SENSITIVE_PROPS_KEY}
      SINGLE_USER_CREDENTIALS_USERNAME: ${NIFI_USERNAME}
      SINGLE_USER_CREDENTIALS_PASSWORD: ${NIFI_PASSWORD}
      NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER: single-user-provider
      NIFI_SECURITY_USER_AUTHORIZER: single-user-authorizer

      NIFI_WEB_PROXY_HOST: ${PROJECT_DOMAIN}:8070
      NIFI_WEB_HTTPS_HOST: 0.0.0.0
      NIFI_WEB_HTTPS_PORT: 8443

      AUTH: tls
      KEYSTORE_PATH: /ssl/keystore.p12
      KEYSTORE_TYPE: PKCS12
      KEYSTORE_PASSWORD: root
      TRUSTSTORE_PATH: /ssl/keystore.p12
      TRUSTSTORE_TYPE: PKCS12
      TRUSTSTORE_PASSWORD: root
