version: "3.8"

services:
  postgres:
    ports:
      - ${ALCHEMY_PORT}:${ALCHEMY_PORT}

  rabbit:
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}

  nifi:
    environment:
      ACTIVATE: ${ACTIVATE_NIFI}
      # NIFI_WEB_HTTPS_HOST: 0.0.0.0
      NIFI_WEB_HTTPS_HOST: ${PROJECT_DOMAIN}
      NIFI_WEB_HTTPS_PORT: 8080
      SINGLE_USER_CREDENTIALS_USERNAME: ${NIFI_USERNAME}
      SINGLE_USER_CREDENTIALS_PASSWORD: ${NIFI_PASSWORD}
