"""empty message

Revision ID: 0d1a8eb64d9d
Revises: fc07fd771a0b
Create Date: 2020-10-21 13:25:05.842402

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0d1a8eb64d9d"
down_revision = "fc07fd771a0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "attribution_group_license_id_fkey", "attribution", type_="foreignkey"
    )
    op.drop_column("attribution", "group_license_id")
    op.add_column("license", sa.Column("group_license_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "license", "group_license", ["group_license_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "license", type_="foreignkey")
    op.drop_column("license", "group_license_id")
    op.add_column(
        "attribution",
        sa.Column("group_license_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "attribution_group_license_id_fkey",
        "attribution",
        "group_license",
        ["group_license_id"],
        ["id"],
    )
    # ### end Alembic commands ###
