"""Extended core models

Revision ID: 10830c7de262
Revises: 923a1d69fb2b
Create Date: 2021-04-29 17:24:19.477469

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "10830c7de262"
down_revision = "923a1d69fb2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("IP", sa.String(length=46), nullable=True),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("failed", sa.Boolean(), nullable=True),
        sa.Column("flushed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.drop_column("token", "hostname")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "token",
        sa.Column(
            "hostname", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )

    op.drop_table("login")
    # ### end Alembic commands ###
