"""empty message

Revision ID: 3a379327cae6
Revises: fdc699214312
Create Date: 2020-07-07 15:32:40.806581

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a379327cae6"
down_revision = "fdc699214312"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attribution", sa.Column("url", sa.String(), nullable=True))
    op.add_column("license", sa.Column("url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("license", "url")
    op.drop_column("attribution", "url")
    # ### end Alembic commands ###
