"""archived label on requests

Revision ID: 4ae0e00df227
Revises: 10830c7de262
Create Date: 2021-05-28 15:29:17.461650

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ae0e00df227"
down_revision = "10830c7de262"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("request", sa.Column("archived", sa.Boolean(), nullable=True))
    op.execute('UPDATE "request" set archived = false')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("request", "archived")
    # ### end Alembic commands ###
