"""archived label on requests

Revision ID: 4ae0e00df227
Revises: 10830c7de262
Create Date: 2021-05-28 15:29:17.461650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae0e00df227'
down_revision = '10830c7de262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('IP', sa.String(length=46), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Boolean(), nullable=True),
    sa.Column('flushed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('request', sa.Column('archived', sa.Boolean(), nullable=True))
    op.execute('UPDATE "request" set archived = false')
    op.drop_column('token', 'hostname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('hostname', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('request', 'archived')
    op.drop_table('login')
    # ### end Alembic commands ###
