"""opendata flag on schedules

Revision ID: 6a109a54d7bc
Revises: 0a8ddda4eb56
Create Date: 2020-11-25 10:52:17.578500

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6a109a54d7bc"
down_revision = "0a8ddda4eb56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedule", sa.Column("opendata", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "opendata")
    # ### end Alembic commands ###
