"""Added mfa_hash column on User

Revision ID: 923a1d69fb2b
Revises: 9ab2d92df45e
Create Date: 2021-02-08 14:35:10.266108

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "923a1d69fb2b"
down_revision = "9ab2d92df45e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("mfa_hash", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "mfa_hash")
    # ### end Alembic commands ###
