"""added params for user configuration

Revision ID: 9ab2d92df45e
Revises: 1cd1cab394b6
Create Date: 2021-01-25 15:11:53.031136

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ab2d92df45e"
down_revision = "1cd1cab394b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("allowed_obs_archive", sa.Boolean(), nullable=True))
    op.add_column(
        "user", sa.Column("allowed_postprocessing", sa.Boolean(), nullable=True)
    )
    op.add_column("user", sa.Column("allowed_schedule", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("max_output_size", sa.BigInteger(), nullable=True))
    op.add_column("user", sa.Column("max_templates", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("request_par_hour", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "request_par_hour")
    op.drop_column("user", "max_templates")
    op.drop_column("user", "max_output_size")
    op.drop_column("user", "allowed_schedule")
    op.drop_column("user", "allowed_postprocessing")
    op.drop_column("user", "allowed_obs_archive")
    # ### end Alembic commands ###
