"""public flag on license group

Revision ID: 9ad4ac3a0c93
Revises: 8f5a81a27483
Create Date: 2020-11-03 14:12:30.030209

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ad4ac3a0c93"
down_revision = "8f5a81a27483"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group_license", sa.Column("is_public", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group_license", "is_public")
    # ### end Alembic commands ###
