"""empty message

Revision ID: 5850215a445e
Revises: 82af248b1e6d
Create Date: 2020-06-22 13:11:56.695089

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5850215a445e"
down_revision = "82af248b1e6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request",
        "error_message",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.add_column("user", sa.Column("amqp_queue", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "amqp_queue")
    op.alter_column(
        "request",
        "error_message",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
