"""local one

Revision ID: bce4b674857e
Revises: 9470f66544d8
Create Date: 2020-01-15 14:04:57.598862

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bce4b674857e"
down_revision = "c126d341bddc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedule", sa.Column("time_delta", sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "time_delta")
    # ### end Alembic commands ###
