"""empty message

Revision ID: c126d341bddc
Revises: 3b205d9c2fa5
Create Date: 2020-01-09 12:52:24.417759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c126d341bddc'
down_revision = '3b205d9c2fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('on_data_ready', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'on_data_ready')
    # ### end Alembic commands ###
