"""Added requests_expiration_days to handle with requests autocleaning

Revision ID: cf0a7cd845b5
Revises: 3a379327cae6
Create Date: 2020-07-29 06:12:00.413435

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf0a7cd845b5"
down_revision = "3a379327cae6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("requests_expiration_days", sa.Integer(), nullable=True)
    )
    op.drop_column("user", "my_custom_field")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "my_custom_field",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user", "requests_expiration_days")
    # ### end Alembic commands ###
