"""Added user.expiration

Revision ID: ea9aac95eb23
Revises: b49e9981a64e
Create Date: 2021-01-07 11:40:49.868309

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea9aac95eb23"
down_revision = "b49e9981a64e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("expiration", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "expiration")
    # ### end Alembic commands ###
