"""Added user.group_id

Revision ID: f343b188fb38
Revises: 9ad4ac3a0c93
Create Date: 2020-11-10 07:47:52.239222

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f343b188fb38"
down_revision = "9ad4ac3a0c93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=True),
        sa.Column("shortname", sa.String(length=64), nullable=True),
        sa.Column("fullname", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shortname"),
        sa.UniqueConstraint("uuid"),
    )
    op.add_column("user", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user", "group", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "group_id")
    op.drop_table("group")
    # ### end Alembic commands ###
