"""relationship between user-group licences

Revision ID: fc07fd771a0b
Revises: bb829894d458
Create Date: 2020-10-16 09:38:30.508532

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc07fd771a0b"
down_revision = "bb829894d458"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grp_licence_association",
        sa.Column("grp_licence_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["grp_licence_id"],
            ["group_license.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grp_licence_association")
    # ### end Alembic commands ###
