import { CodeDescPair } from "@app/types";

export const LEVELTYPES: CodeDescPair[] = [
  { code: "1", desc: "Ground or Water Surface" },
  { code: "2", desc: "Cloud Base Level" },
  { code: "3", desc: "Level of Cloud Tops" },
  { code: "4", desc: "Level of 0C Isotherm" },
  {
    code: "5",
    desc: "Level of Adiabatic Condensation Lifted from the Surface",
  },
  { code: "6", desc: "Maximum Wind Level" },
  { code: "7", desc: "Tropopause" },
  { code: "8", desc: "Nominal Top of the Atmosphere" },
  { code: "9", desc: "Sea Bottom" },
  { code: "20", desc: "Isothermal Level" },
  { code: "100", desc: "Isobaric Surface" },
  { code: "101", desc: "Layer between two isobaric surfaces" },
  { code: "102", desc: "Mean sea level " },
  { code: "103", desc: "Specified altitude above mean sea level" },
  { code: "104", desc: "Layer between two specified altitudes" },
  { code: "105", desc: "Specified height level above ground" },
  { code: "106", desc: "Layer between two specified height levels" },
  { code: "107", desc: "Sigma level" },
  { code: "108", desc: "Layer between two sigma levels" },
  { code: "109", desc: "Hybrid level" },
  { code: "110", desc: "Layer between two hybrid levels" },
  { code: "111", desc: "Depth below land surface" },
  { code: "112", desc: "Layer between two depths below land" },
  { code: "113", desc: "Isentropic (theta) level " },
  { code: "114", desc: "Layer between two isentropic levels" },
  { code: "115", desc: "Level at specified pressure difference" },
  {
    code: "116",
    desc: "Layer between two levels at specified pressure differences from ground to level",
  },
  { code: "117", desc: "Potential vorticity surface" },
  { code: "119", desc: "ETA* level" },
  { code: "120", desc: "Layer between two ETA* levels" },
  { code: "121", desc: "Layer between two isobaric surfaces (high precision)" },
  { code: "125", desc: "Specified height level above ground (high precision)" },
  {
    code: "127",
    desc: "Satellite Spectral band (as defined by INPE/CPTEC and used by ECMWF)",
  },
  { code: "128", desc: "Layer between two sigma levels (high precision)" },
  {
    code: "141",
    desc: "Layer between two isobaric surfaces (mixed precision)",
  },
  { code: "160", desc: "Depth below sea level" },
  { code: "200", desc: "Entire atmosphere (considered as a single layer)" },
  { code: "201", desc: "Entire ocean (considered as a single layer)" },
  { code: "210", desc: "Isobaric surface (high precision) (ECMWF extension)" },
];
