inputs:
  project:
    description: "Project name"
  dataset_url:
    description: "URL of the dataset to be installed"
runs:
  using: "composite"
  steps:
    - run: |
        wget --quiet ${{ inputs.dataset_url }}/arkimet.conf -O data/arkimet_conf/arkimet.conf;
        wget --quiet ${{ inputs.dataset_url }}/arkimet_summary_CCBY_COMPLIANT.json -O data/arkimet_conf/arkimet_summary_filtered_CCBY_COMPLIANT.json;
        wget --quiet ${{ inputs.dataset_url }}/dballe_summary_filtered_CCBY_COMPLIANT.json -O data/arkimet_conf/dballe_summary_filtered_CCBY_COMPLIANT.json;
        wget --quiet ${{ inputs.dataset_url }}/sample.bufr -O data/arkimet_conf/sample.bufr;
        wget --quiet ${{ inputs.dataset_url }}/arkimet.zip;
        unzip -q arkimet.zip -d data/;
        ls -l data/arkimet;
        ls -l data/arkimet_conf;
        mkdir data/user_repo/templates_for_pp;
        wget --quiet ${{ inputs.dataset_url }}/template_for_spare_point.zip -O data/user_repo/templates_for_pp/template_for_spare_point.zip;

        rapydo --testing -e FTP_USER=ftpuser init --force

        rapydo pull --quiet;
        rapydo install buildx
        rapydo build --force;
        rapydo add task test_task;
        rapydo start;
        rapydo shell backend 'restapi wait';

        echo "dbadb wipe --dsn=postgresql://\$ALCHEMY_USER:\$ALCHEMY_PASSWORD@\$ALCHEMY_HOST:\$ALCHEMY_PORT/DBALLE" > init.sh;
        echo "dbadb import --dsn=postgresql://\$ALCHEMY_USER:\$ALCHEMY_PASSWORD@\$ALCHEMY_HOST:\$ALCHEMY_PORT/DBALLE --type=bufr /arkimet/config/sample.bufr" >> init.sh;
        cname=$(docker ps --format '{{.Names}}' | grep "backend")
        docker cp init.sh ${cname}:/tmp/init.sh;
        rapydo shell backend 'bash /tmp/init.sh';
      shell: bash
